# /getitemshop - (permission: getitemshop.use)
# /getitemshop add {username} {service_id} - (permission: getitemshop.admin)
# /getitemshop remove {username} {service_id} - (permission: getitemshop.admin)
mysql:
  host: localhost
  username: root
  password: ""
  database: itemshop
  port: 3306
  ssl: false

command: "getitemshop"
# cooldown at second
cooldown: 5

inv:
  size: 36
  title: "&0Itemshop"

lang:
  no-services: "&cNie posiadasz uslugi!"
  cooldown-cmd: "&cMusisz poczekac {time} sek!"
  successfully-recived: "&aPomyslnie odebrano {service}!"

serv-slots: [10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25]

background:
  '1':
    material: BLACK_STAINED_GLASS_PANE
    displayname: "&7"
    lore: []
    slots: [0,1,2,3,4,5,6,7,8,9,17,18,26,27,28,29,30,31,32,33,34,35]

services:
  key_1:
    name: "&aVip na 7 dni"
    item:
      material: PAPER
      displayname: "&e * * &fV I P &e* *"
      lore:
        - "&7"
        - "&eKliknij aby odebrac!"
      glow: true
    commands:
      - "say Gracz {player} odebral vipa!"
  key_2:
    name: "&5Klucz epicki"
    item:
      material: PAPER
      displayname: "&5 * * &fKlucz EPICKI &5* *"
      lore:
        - "&7"
        - "&eKliknij aby odebrac!"
      glow: true
    commands:
      - "say Gracz {player} odebral klucze!"